In [2]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [7]:

# square vs. rectangular
S = np.random.randn(5,5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4,4))
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(2,4)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=0)
print(C)

[[[ 1.04875225e-01  4.61793150e-02 -2.72421119e-01  3.23252929e-01
    8.39797184e-01]
  [ 6.60443528e-01  5.65250200e-01 -3.23719193e-01 -1.16315606e+00
    1.60488529e+00]
  [-1.64143753e+00  3.45224140e-01  3.32427598e-01  1.00806582e+00
   -7.49567636e-01]
  [ 1.72012877e+00 -8.17267140e-01  7.29526707e-01  1.92287132e+00
   -7.07699767e-01]
  [ 2.70309060e-01  1.41044570e+00  1.78613856e+00  2.48834612e+00
   -2.84755000e-01]]

 [[-6.42154802e-01  8.94161808e-01 -1.20158207e+00 -3.91611945e-01
   -6.51670239e-01]
  [-4.01969485e-01 -4.81899087e-01 -4.10706740e-01  1.21985842e+00
   -1.30084771e-01]
  [-7.02306787e-01  1.97956654e+00 -1.61958983e+00  7.44750696e-01
   -5.15198255e-01]
  [-3.25859854e-01  7.16412990e-01 -5.72757852e-01  6.55897651e-01
   -1.23092768e+00]
  [ 8.36381093e-01 -1.80900344e-01 -5.22467877e-01 -1.37266576e+00
    3.84886876e-01]]

 [[ 1.02808151e+00  6.96002426e-01  5.81792351e-01 -2.33103572e+00
   -4.83214687e-02]
  [ 2.29676768e-01  2.56905810e-02 -2.2


---
# VIDEO: Matrix addition and subtraction
---


In [10]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,4)
C = np.random.randn(5,4)

# try to add them
A+B
A+C



# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)

[[-1.4312669  -0.33780991 -0.72743846  1.69188486 -1.09101515]
 [ 0.24995871  1.08870958  1.08856997  0.05497165  1.25928134]
 [-0.39824871  1.06606545  0.47340812 -0.16690527 -1.79828664]
 [-1.62704912  0.35472308  0.71280489 -0.83693183  2.0089046 ]
 [-1.82214094 -1.883722    1.6688946  -0.55279959  0.35484905]]
 
[[-1.4012669  -0.33780991 -0.72743846  1.69188486 -1.09101515]
 [ 0.24995871  1.11870958  1.08856997  0.05497165  1.25928134]
 [-0.39824871  1.06606545  0.50340812 -0.16690527 -1.79828664]
 [-1.62704912  0.35472308  0.71280489 -0.80693183  2.0089046 ]
 [-1.82214094 -1.883722    1.6688946  -0.55279959  0.38484905]]


(None, None, None)


---
# VIDEO: Matrix-scalar multiplication
---


In [9]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# VIDEO: Transpose

In [ ]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

In [ ]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!



---
# VIDEO: Diagonal and trace
---


In [ ]:

M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)


---
# VIDEO: Broadcasting matrix arithmetic
---


In [ ]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ');

In [ ]:
# broadcast on the rows
# print(A+r), print(' ')

# broadcast on the columns
print(A+c)
# print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors
