In [3]:
import numpy as np

In [3]:
s = 0.3
A = np.random.randn(2, 3)
B = np.random.randn(2, 3)

res1 = s * (A + B)
res2 = s * A + s * B

print(res1)
print(res2)

[[ 0.51494802  0.52096222 -0.27033615]
 [ 0.01568375 -0.47052521 -0.13067625]]
[[ 0.51494802  0.52096222 -0.27033615]
 [ 0.01568375 -0.47052521 -0.13067625]]


In [5]:
A = np.random.randn(4, 4)
B = np.random.randn(4, 4)

print(np.trace(A) + np.trace(B))
print(np.trace(A + B))

Lambda = np.random.randn(1)

print(np.trace(Lambda * A))
print(Lambda * np.trace(A))

0.0497930916944318
0.0497930916944318
-1.041287764549335
[-1.04128776]


In [18]:
A = np.round(np.random.randn(5, 4))
B = np.round(np.random.randn(4, 5))

M = np.zeros(5)

print(A.shape[1])

for i in range(A.shape[1]):
    M = M + np.outer(A[:, i], B[i, :]) 
    
print(M)
print(A@B)

4
[[-1.  1.  0. -1.  0.]
 [ 0.  4. -2.  0. -4.]
 [-4. -2. -3. -1.  0.]
 [ 2. -2.  2. -2.  2.]
 [-3. -1. -2.  3.  0.]]
[[-1.  1.  0. -1.  0.]
 [ 0.  4. -2.  0. -4.]
 [-4. -2. -3. -1.  0.]
 [ 2. -2.  2. -2.  2.]
 [-3. -1. -2.  3.  0.]]
