In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [35]:
v1 = np.random.randn(100)
v2 = np.random.randn(100)

res1 = np.dot(v1, v2)
res2 = np.dot(v2, v1)

print(res1, res2, res1 - res2)

v = np.array([2, 4])
w = np.array([3, 5])

print(np.dot(v, w), np.dot(w, v), w@v, v@w)


-0.6163293026701577 -0.6163293026701577 0.0
26 26 26 26


In [34]:
v1 = np.array([-3,4,6])
v2 = np.array([3, 6, -3])
s1 = 2
s2 = 3
print('Original dot product: ' + str(np.dot(v1, v2)))
print('Scaled dot product: ' + str(np.dot(v1 * s1, v2 * s2)))

Original dot product: -3
Scaled dot product: -18


In [42]:
m1 = np.array([[1, 2],[3, 4]])
m2 = np.array([[3, 4],[1, 2]])

np.dot(m1, m2)
np.dot(m2, m1)

m1.T * m2
m2.T * m1

np.multiply(m1.T, m2)

array([[ 3, 12],
       [ 2,  8]])

In [55]:
x1 = np.arange(3.0).reshape((3, 1))
x2 = np.arange(3.0).reshape((3, 1))
print(np.multiply(x1, x2))
x1 * x2
np.dot(x2, x1.T)


[[0.]
 [1.]
 [4.]]


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [20]:
# m1 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
# m2 = np.array([[4, 4, 4], [5, 5, 5], [6, 6, 6]])

m1 = np.round(np.random.randn(3, 2, 2))
m2 = np.round(np.random.randn(3, 2, 2))

print(m1)
print(' ')
print(m2)
print(' ')


print('np.multiply')
print(' ')
print(np.multiply(m1, m2))
print(' ')
print(np.multiply(m2, m1))
print(' ')

print('m1 * m2')
print(m1 * m2)
print(' ')
print(m2 * m1)
print(' ')

print('np.dot(m1, m2)')
print(' ')
print(np.dot(m1, m2))
print(' ')
# print(np.dot(m2, m1))
# print(' ')

print('np.matmul')
print(' ')
print(np.matmul(m1, m2))
print(' ')
print(np.matmul(m2, m1))






[[[-0. -1.]
  [-1.  0.]]

 [[ 2. -1.]
  [-0.  0.]]

 [[-2.  1.]
  [-0.  0.]]]
 
[[[-2. -1.]
  [-1. -2.]]

 [[-2.  2.]
  [ 2. -0.]]

 [[-0.  1.]
  [ 4.  1.]]]
 
np.multiply
 
[[[ 0.  1.]
  [ 1. -0.]]

 [[-4. -2.]
  [-0. -0.]]

 [[ 0.  1.]
  [-0.  0.]]]
 
[[[ 0.  1.]
  [ 1. -0.]]

 [[-4. -2.]
  [-0. -0.]]

 [[ 0.  1.]
  [-0.  0.]]]
 
m1 * m2
[[[ 0.  1.]
  [ 1. -0.]]

 [[-4. -2.]
  [-0. -0.]]

 [[ 0.  1.]
  [-0.  0.]]]
 
[[[ 0.  1.]
  [ 1. -0.]]

 [[-4. -2.]
  [-0. -0.]]

 [[ 0.  1.]
  [-0.  0.]]]
 
np.dot(m1, m2)
 
[[[[ 1.  2.]
   [-2.  0.]
   [-4. -1.]]

  [[ 2.  1.]
   [ 2. -2.]
   [ 0. -1.]]]


 [[[-3.  0.]
   [-6.  4.]
   [-4.  1.]]

  [[ 0.  0.]
   [ 0.  0.]
   [ 0.  0.]]]


 [[[ 3.  0.]
   [ 6. -4.]
   [ 4. -1.]]

  [[ 0.  0.]
   [ 0.  0.]
   [ 0.  0.]]]]
 
np.matmul
 
[[[ 1.  2.]
  [ 2.  1.]]

 [[-6.  4.]
  [ 0.  0.]]

 [[ 4. -1.]
  [ 0.  0.]]]
 
[[[ 1.  2.]
  [ 2.  1.]]

 [[-4.  2.]
  [ 4. -2.]]

 [[ 0.  0.]
  [-8.  4.]]]
