In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
v1 = np.round(20 * np.random.rand(4))
v2 = np.round(20 * np.random.rand(4))

print(v1)
print(' ')

print(v2)
print(' ')

v1l = np.linalg.norm(v1)
v2l = np.linalg.norm(v2)

print(v1l)
print(' ')

print(v2l)
print(' ')

v1dv2 = abs(np.dot(v1, v2))


print(v1dv2)
print(' ')

muv1 = 1 / v1l
muv2 = 1 / v2l


print(muv1, muv2)
print(' ')

v1m = v1 * muv1
v2m = v2 * muv2


print(v1m, v2m)
print(' ')

v1ml = np.linalg.norm(v1m)
v2ml = np.linalg.norm(v2m)

print(v1ml, v2ml)
print(' ')

v1dv2_nor = abs(np.dot(v1m, v2m))

print(v1dv2_nor)
print(' ')


[18. 12. 10. 19.]
 
[ 2. 14. 16.  1.]
 
30.479501308256342
 
21.37755832643195
 
383.0
 
0.03280893574623933 0.0467780269724988
 
[0.59056084 0.39370723 0.32808936 0.62336978] [0.09355605 0.65489238 0.74844843 0.04677803]
 
0.9999999999999999 1.0
 
0.5878043787289238
 
